Added steps for Github and Git setup
CarletonSLAM/git-workshop pull request #1
Opened 2017-09-14 02:45 UTC by irushavm

2017-09-14 02:45 UTC, irushavm commented
@JackyChiu

2017-09-14 13:47 UTC, JackyChiu approved these changes

2017-09-15 01:41 UTC, JackyChiu requested changes
https://github.com/googlesamples/md2googleslides

Can you add `---` to your stuff so it can work with slides? (`---` seperates slides)

Also move your stuff from `.github/images` to just `.github`

2017-09-15 14:14 UTC, JackyChiu approved these changes

2017-09-15 14:14 UTC, merged

2017-09-15 14:16 UTC, JackyChiu commented
merging bc 

![sanic](https://ih0.redbubble.net/image.32562860.9057/flat,800x800,070,f.jpg)